/*
 * Orm4Qt - An Object Relational Mapping Library for the Qt Framework
 * Copyright (c) 2014, Michael Dougras da Silva, All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library.
 */

#include "personform.h"
#include "ui_personform.h"
#include <QFileDialog>
#include <QMessageBox>
#include <QFile>
#include <QDataStream>

/**
 * Constructor with parent initialization
 * @param parent
 * The QWidget parent of this instance
 * @param person
 * The person register used to fill the form
 */
PersonForm::PersonForm(QWidget *parent, const Person &person) :
    QDialog(parent),
    ui(new Ui::PersonForm)
{
    ui->setupUi(this);

    //Connect the buttons of upload and download to the slots of upload and download
    connect(ui->resumeDownloadButton, SIGNAL(clicked()), this, SLOT(downloadResume()));
    connect(ui->resumeUploadButton, SIGNAL(clicked()), this, SLOT(uploadResume()));

    //Adjust the person register used to fill the form
    setPerson(person);
}

/**
 * Destructor
 */
PersonForm::~PersonForm()
{
    delete ui;
}

/**
 * Getter of the person register
 * @return
 * The person register generated by the form data
 */
Person PersonForm::person() const
{
    return m_person;
}

/**
 * Set the register used to fill the form
 * @param person
 * The new register used to fill the form
 */
void PersonForm::setPerson(const Person &person)
{
    m_person = person;
    updateFormData();
}

/**
 * Update the form data with the values of the person properties
 */
void PersonForm::updateFormData()
{
    ui->nameEdit->setText(m_person.name());
    ui->emailEdit->setText(m_person.email());
    ui->birthdayEdit->setDate(m_person.birthday());
    ui->balanceEdit->setValue(m_person.balance());
    ui->ageEdit->setValue(m_person.age());
    ui->resumeDownloadButton->setEnabled(!m_person.resume().isNull());
}

/**
 * Update the person register based on the form data
 */
void PersonForm::updatePersonData()
{
    m_person.setName(ui->nameEdit->text());
    m_person.setEmail(ui->emailEdit->text());
    m_person.setBirthday(ui->birthdayEdit->date());
    m_person.setBalance(ui->balanceEdit->value());
    m_person.setAge(ui->ageEdit->value());
}

/**
 * Upload the resumé file
 */
void PersonForm::uploadResume()
{
    if(!m_person.resume().isNull())
    {
        int response = QMessageBox::question(this, "Replacing resumé",
                              "This person already has a resumé. Do you want to replace it?", QMessageBox::Yes | QMessageBox::No, QMessageBox::No);
        if(response == QMessageBox::No)
            return;
    }
    QString filename = QFileDialog::getOpenFileName(this, "Choose the resumé file", QDir::homePath(), "PDF(*.pdf)");
    if(!filename.isNull())
    {
        QFile file(filename);
        if(file.open(QIODevice::ReadOnly))
        {
            m_person.setResume(file.readAll());
            ui->resumeDownloadButton->setEnabled(!m_person.resume().isNull());
            file.close();
            QMessageBox::information(this, "Resumé uploaded", "The file was uploaded!");
        }
        else
        {
            QMessageBox::critical(this, "Can't open the file", "An error occurred while reading the file. The resumé wasn't updated.");
        }
    }
}

/**
 * Download the resumé file from the database
 */
void PersonForm::downloadResume()
{
    QString filename = QFileDialog::getSaveFileName(this, "Choose where to save the resumé", QDir::homePath(), "PDF (*.pdf)");
    if(!filename.isNull())
    {
        QFile file(filename);
        if(file.open(QIODevice::WriteOnly | QIODevice::Truncate))
        {
            QDataStream stream(&file);
            stream << m_person.resume();
            file.close();
            QMessageBox::information(this, "Resumé downloaded", QString("The resumé was downloaded to \"%1\".").arg(filename));
        }
        else
        {
            QMessageBox::critical(this, "Can't save the resumé", "An error occurred while saving the resumé.");
        }
    }
}

